### ISSUE TITLE
Small differences on author's name report different authors

### ISSUE THREAD

**Issue by chipironcin** [Kikobeats/git-authors-cli#1]
My name has special characters. Depending on the system I do the commit it will use a different name. See the example below:
```
  81	Jorge Marin <Jorge.Marin@company.com>
  15	Jorge Marín <Jorge.Marin@company.com>
  7	Jorge Mar <Jorge.Marin@company.com>
```

This is obviously a problem with configuration of the different systems I use to add commits to the repository but it would be great if we can include a flag in this tool to try to merge contributors that use the same email.

Maybe something like `--merge` or `--by-email`. WDYT? I am keen to implement it by myself if owners agree.

**Comment by Kikobeats** [comment]
A simple solution could use the author with the major number of commits

**Comment by chipironcin** [comment]
Thank you @Kikobeats 
My original issue has been resolved.
