### ISSUE TITLE
Provide a way to print authors without saving to package.json

### ISSUE THREAD

**Issue by trongthanh** [Kikobeats/git-authors-cli#17]
Currently, without adding `--save` argument, the command still save the contributors list to `package.json` file if it exist.

Please provide a new argument so we can print out only the git authors list without saving to package.json, or switch the `--save` argument to `false` by default (but this change will break existing scripts).

**Comment by Kikobeats** [comment]
did you try to pass `--no-save`?

**Comment by trongthanh** [comment]
Woa, I didn't know this flag existed. It's not documented anywhere.
