### ISSUE TITLE
Provide a way to ignore Github user's email alias

### ISSUE THREAD

**Issue by trongthanh** [Kikobeats/git-authors-cli#34]
By default, Github user has this option on in their emails setting: `Keep my email addresses private`. This will hide user's emails in Github web UI's operations such as PR merge, file edit and commit from Web editor... 

As a result, when we run this command, we've got NEW user as well as obfuscated email address appear in the package.json's contributors list, for example:

```diff
+  "Thanh Tran <99478251+thanhtran-ct@users.noreply.github.com>"
```

Can we have an extra param (such as `--ignore-pattern users.noreply.github.com`) that will skip any commit authors having such pattern from output / addition to packakge.json?

**Comment by Kikobeats** [comment]
I'm happy to accept a PR over this 🙂

**Comment by trongthanh** [comment]
I'll see to this when got time.
